spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          password: tpmall
          url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
          username: tpmall